### ISSUE TITLE
Not able to seed files with tor always mode

### ISSUE THREAD

**Issue by Nostradamos** [HelloZeroNet/ZeroUp#1]
I am able to publish a new zite with tor always mode, but not to seed any files with ZeroUp or any fork of it (Youtube, kopykate).
EDIT: Upload works now, but i'm not sure if someone between is doing the active/passive tunneling.

**Comment by HelloZeroNet** [comment]
If you using Tor mode, then only other Tor users will able to connect to you, so it can be a bit problematic with initial seeding.

I'm also planning to add built-in tor client to Linux and Mac. (Currently only windows has it)

**Comment by Nostradamos** [comment]
Thanks for your reply, could you clarify whether that means you can only download from a tor only seed if you're using the tor browser, or is it enough to tunnel zeronet through tor (with tor always on)?
And besides that, is it enough to let zeronet run in the background to seed, or is it needed to have the website opened up in a browser?

**Comment by HelloZeroNet** [comment]
The browser does not matter and you can close it any time, the ZeroNet client will seed it in the background.

Possible cases when you upload an optional file:
 - You have opened port: Anyone can connect to you
 - You don't have opened port, but the Tor status is Available or you using it in Tor: Always mode: Only clients with Tor: Always or Available can connect to you
 - No opened port and Tor status is disabled: Probably no one will able to download you uploaded optional file
