### ISSUE TITLE
Allow files be searchable in ZeroHello newsfeed?

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroUp#2]
Hello,

i am connected to ZeroUp and uploaded a file there and i can not find it when i search its name on ZeroHello newsfeed.

Kaffie made a search tool for ZeroUp [here](http://127.0.0.1:43110/1FEH3VjjKoDTXSpUA1G4xpB7WFnfQ48oVC/)

**Comment by ghost** [comment]
I believe this is because newsfeed search only searches things that would be listed in the newsfeed, which are things that you have to follow. afaik, ZeroUp doesn't have the follow feature for NewsFeed yet.

**Comment by tangdou1** [comment]
I think this can be closed now because the feature has been realized.
