### ISSUE TITLE
Can't see my upload

### ISSUE THREAD

**Issue by mcl12345** [HelloZeroNet/ZeroUp#3]
Hi,

I uploaded a targz file but I can't see my uploads in "My uploads"

**Comment by HelloZeroNet** [comment]
I can't reproduce the problem.
What was the file name? Does it got listed in "Latest" section?

**Comment by mcl12345** [comment]
"Latest" section doesn't work

**Comment by mcl12345** [comment]
When I click on the "Latest" section the button "show more" doesn't work

**Comment by mcl12345** [comment]
The file is 
Query: celtic
1 results
0. Celtic Gate – Into a magical forest - Celtic Music.tar
Celtic Gate Into a magical forest - Celtic Music.tar.gz
null | 1CSqCUFUV213NwCXDAAXEqPBvhmnDkq56e
File Size: 146.52mb, Date Uploaded: 17/03/2018 à 11:52:39

**Comment by mcl12345** [comment]
Sometimes the "Latest" section doesn't work

**Comment by HelloZeroNet** [comment]
I can't find it, have you uploaded it to site http://127.0.0.1:43110/1uPLoaDwKzP6MCGoVzw48r4pxawRBdmQc ?

Do you see any error in js console? (F12 > Console)

**Comment by mcl12345** [comment]
`have you uploaded it to site http://127.0.0.1:43110/1uPLoaDwKzP6MCGoVzw48r4pxawRBdmQc ?`
yes

**Comment by mcl12345** [comment]
the error with F12:
TypeError: this.row.cert_user_id is null
